// 66 canonical books. id is 1-based ordinal so users can type "1..66" on the keypad.
// abbr is a 2-3 char label suitable for the LCD (standard Chinese Union Version abbreviations).
export const BOOKS = Object.freeze([
  { id: 1,  name: "Genesis",         abbr: "创",   chapters: 50,  testament: "OT" },
  { id: 2,  name: "Exodus",          abbr: "出",   chapters: 40,  testament: "OT" },
  { id: 3,  name: "Leviticus",       abbr: "利",   chapters: 27,  testament: "OT" },
  { id: 4,  name: "Numbers",         abbr: "民",   chapters: 36,  testament: "OT" },
  { id: 5,  name: "Deuteronomy",     abbr: "申",   chapters: 34,  testament: "OT" },
  { id: 6,  name: "Joshua",          abbr: "书",   chapters: 24,  testament: "OT" },
  { id: 7,  name: "Judges",          abbr: "士",   chapters: 21,  testament: "OT" },
  { id: 8,  name: "Ruth",            abbr: "得",   chapters: 4,   testament: "OT" },
  { id: 9,  name: "1 Samuel",        abbr: "撒上", chapters: 31,  testament: "OT" },
  { id: 10, name: "2 Samuel",        abbr: "撒下", chapters: 24,  testament: "OT" },
  { id: 11, name: "1 Kings",         abbr: "王上", chapters: 22,  testament: "OT" },
  { id: 12, name: "2 Kings",         abbr: "王下", chapters: 25,  testament: "OT" },
  { id: 13, name: "1 Chronicles",    abbr: "代上", chapters: 29,  testament: "OT" },
  { id: 14, name: "2 Chronicles",    abbr: "代下", chapters: 36,  testament: "OT" },
  { id: 15, name: "Ezra",            abbr: "拉",   chapters: 10,  testament: "OT" },
  { id: 16, name: "Nehemiah",        abbr: "尼",   chapters: 13,  testament: "OT" },
  { id: 17, name: "Esther",          abbr: "斯",   chapters: 10,  testament: "OT" },
  { id: 18, name: "Job",             abbr: "伯",   chapters: 42,  testament: "OT" },
  { id: 19, name: "Psalms",          abbr: "诗",   chapters: 150, testament: "OT" },
  { id: 20, name: "Proverbs",        abbr: "箴",   chapters: 31,  testament: "OT" },
  { id: 21, name: "Ecclesiastes",    abbr: "传",   chapters: 12,  testament: "OT" },
  { id: 22, name: "Song of Solomon", abbr: "歌",   chapters: 8,   testament: "OT" },
  { id: 23, name: "Isaiah",          abbr: "赛",   chapters: 66,  testament: "OT" },
  { id: 24, name: "Jeremiah",        abbr: "耶",   chapters: 52,  testament: "OT" },
  { id: 25, name: "Lamentations",    abbr: "哀",   chapters: 5,   testament: "OT" },
  { id: 26, name: "Ezekiel",         abbr: "结",   chapters: 48,  testament: "OT" },
  { id: 27, name: "Daniel",          abbr: "但",   chapters: 12,  testament: "OT" },
  { id: 28, name: "Hosea",           abbr: "何",   chapters: 14,  testament: "OT" },
  { id: 29, name: "Joel",            abbr: "珥",   chapters: 3,   testament: "OT" },
  { id: 30, name: "Amos",            abbr: "摩",   chapters: 9,   testament: "OT" },
  { id: 31, name: "Obadiah",         abbr: "俄",   chapters: 1,   testament: "OT" },
  { id: 32, name: "Jonah",           abbr: "拿",   chapters: 4,   testament: "OT" },
  { id: 33, name: "Micah",           abbr: "弥",   chapters: 7,   testament: "OT" },
  { id: 34, name: "Nahum",           abbr: "鸿",   chapters: 3,   testament: "OT" },
  { id: 35, name: "Habakkuk",        abbr: "哈",   chapters: 3,   testament: "OT" },
  { id: 36, name: "Zephaniah",       abbr: "番",   chapters: 3,   testament: "OT" },
  { id: 37, name: "Haggai",          abbr: "该",   chapters: 2,   testament: "OT" },
  { id: 38, name: "Zechariah",       abbr: "亚",   chapters: 14,  testament: "OT" },
  { id: 39, name: "Malachi",         abbr: "玛",   chapters: 4,   testament: "OT" },
  { id: 40, name: "Matthew",         abbr: "太",   chapters: 28,  testament: "NT" },
  { id: 41, name: "Mark",            abbr: "可",   chapters: 16,  testament: "NT" },
  { id: 42, name: "Luke",            abbr: "路",   chapters: 24,  testament: "NT" },
  { id: 43, name: "John",            abbr: "约",   chapters: 21,  testament: "NT" },
  { id: 44, name: "Acts",            abbr: "徒",   chapters: 28,  testament: "NT" },
  { id: 45, name: "Romans",          abbr: "罗",   chapters: 16,  testament: "NT" },
  { id: 46, name: "1 Corinthians",   abbr: "林前", chapters: 16,  testament: "NT" },
  { id: 47, name: "2 Corinthians",   abbr: "林后", chapters: 13,  testament: "NT" },
  { id: 48, name: "Galatians",       abbr: "加",   chapters: 6,   testament: "NT" },
  { id: 49, name: "Ephesians",       abbr: "弗",   chapters: 6,   testament: "NT" },
  { id: 50, name: "Philippians",     abbr: "腓",   chapters: 4,   testament: "NT" },
  { id: 51, name: "Colossians",      abbr: "西",   chapters: 4,   testament: "NT" },
  { id: 52, name: "1 Thessalonians", abbr: "帖前", chapters: 5,   testament: "NT" },
  { id: 53, name: "2 Thessalonians", abbr: "帖后", chapters: 3,   testament: "NT" },
  { id: 54, name: "1 Timothy",       abbr: "提前", chapters: 6,   testament: "NT" },
  { id: 55, name: "2 Timothy",       abbr: "提后", chapters: 4,   testament: "NT" },
  { id: 56, name: "Titus",           abbr: "多",   chapters: 3,   testament: "NT" },
  { id: 57, name: "Philemon",        abbr: "门",   chapters: 1,   testament: "NT" },
  { id: 58, name: "Hebrews",         abbr: "来",   chapters: 13,  testament: "NT" },
  { id: 59, name: "James",           abbr: "雅",   chapters: 5,   testament: "NT" },
  { id: 60, name: "1 Peter",         abbr: "彼前", chapters: 5,   testament: "NT" },
  { id: 61, name: "2 Peter",         abbr: "彼后", chapters: 3,   testament: "NT" },
  { id: 62, name: "1 John",          abbr: "约一", chapters: 5,   testament: "NT" },
  { id: 63, name: "2 John",          abbr: "约二", chapters: 1,   testament: "NT" },
  { id: 64, name: "3 John",          abbr: "约三", chapters: 1,   testament: "NT" },
  { id: 65, name: "Jude",            abbr: "犹",   chapters: 1,   testament: "NT" },
  { id: 66, name: "Revelation",      abbr: "启",   chapters: 22,  testament: "NT" },
]);

export function getBookById(id) {
  return BOOKS.find(b => b.id === id) ?? null;
}
